### PR TITLE
 Detect and recover from ping timeouts

### PR DESCRIPTION
**Pull request by Ajnasz**
Port server pings from:
https://github.com/martynsmith/node-irc/commit/c91436f98cd49a5aefcd1f7287bef120519f5998

### CODE REVIEW

**Comment by em92** [comment]
Hi!
Tried out your fork to resolve my problem with client disconnecting with ping timeout. Deployed on Jan 25, 2018. App threw this exception today early morning:
```/home/ubuntu/highman-special/node_modules/irc/lib/irc.js:998
    if (self.conn.requestedDisconnect)
                 ^

TypeError: Cannot read property 'requestedDisconnect' of null
    at Client.reconnect [as _reconnect] (/home/ubuntu/highman-special/node_modules/irc/lib/irc.js:998:18)
    at Socket.<anonymous> (/home/ubuntu/highman-special/node_modules/irc/lib/irc.js:982:14)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at TCP._onclose (net.js:469:12)
```

https://github.com/Ajnasz/node-irc/blob/a4afb364db01fcf46f4cae45ad5bcde71393a32c/lib/irc.js#L998

So, it looks like client tried to reconnect, but failed. I think the reason was this:
https://github.com/Ajnasz/node-irc/blob/a4afb364db01fcf46f4cae45ad5bcde71393a32c/lib/irc.js#L1023

Settings are simple.
```
var client = new irc.Client('irc.quakenet.org', 'eugene_irc_bot', {
  stripColors: true,
  channels: ['#tdmpickup']
});
```

On my side, to resolve this issue, I removed line where `this.conn = null`.

**Comment by em92** [comment]
Btw, original https://github.com/martynsmith/node-irc/commit/c91436f98cd49a5aefcd1f7287bef120519f5998 in method `Client.prototype.connectionTimedOut` runs
`self.conn.emit('close');`

You implementation method runs `self.end();` which runs `this.conn.destroy()`. Why not `this.conn.emit('close');` in this method instead of `this.conn.destroy()`?

**Comment by Ajnasz** [comment]
> On my side, to resolve this issue, I removed line where this.conn = null.

Yes, this looks like working. Thanks! I pushed that change.

> Btw, original martynsmith/node-irc@c91436f in method Client.prototype.connectionTimedOut runs
self.conn.emit('close');

That's an older version, see https://github.com/martynsmith/node-irc/commit/b47c7dbbefd9e9e7997fcb4d924dc5d966d913cb#diff-5b86bf0337d73c3e3c4c7660393192cc

> You implementation method runs self.end(); which runs this.conn.destroy(). Why not this.conn.emit('close'); in this method instead of this.conn.destroy()?

`self.end` also  stops the cyclingPingTimer

**Comment by em92** [comment]
So far so good. Voting for merge.

**Comment by Half-Shot** [comment]
Sorry that we left this to rot for ages, the codebase has moved on since so we're not going to be able to merge this one cleanly. Please re-open if you think this is still a concern.

**Pull request closed without merging**
