### PR TITLE
there won't always be a space after `sasl` in CAP ACK

### PR DESCRIPTION
**Pull request by jesopo**
see #45

### CODE REVIEW

**Comment by jesopo** [comment]
I can see how this happened; if you look at the `CAP ACK` output from the test server in `test.js`:

```
raw:  { prefix: 'irc.dollyfish.net.nz',
  server: 'irc.dollyfish.net.nz',
  command: 'CAP',
  rawCommand: 'CAP',
  commandType: 'normal',
  args: [ '*', 'ACK', 'sasl ' ] }
```

note, the space after sasl in `args`

but if we point it at a different ircd...

```
raw:  { prefix: 'irc.darwin.network',
  server: 'irc.darwin.network',
  command: 'CAP',
  rawCommand: 'CAP',
  commandType: 'normal',
  args: [ '*', 'ACK', 'sasl' ] }
```

**Comment by jesopo** [comment]
additionally, `CAP ACK` lines look like this when you `CAP REQ` more than just SASL:

`:server CAP * ACK :account-notify sasl multi-prefix`

**Comment by Half-Shot** [comment]
good catch, I think this is fine. @jesopo can I get a sign off from you as per https://github.com/matrix-org/matrix-appservice-irc/blob/master/CONTRIBUTING.md#making-pull-requests? 

(Sorry it's not clear about that in the README, E_TOOMANYPROJECTS)

**Comment by jesopo** [comment]
signed off

**Pull request merged**
